services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      network: host

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgres/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DATABASE_USERNAME}" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

volumes:
  db:
    driver: local
