[config]
default_to_workspace = false

[env]
HOST = "0.0.0.0"
PORT = 8080
DATABASE_USERNAME = "app"
DATABASE_PASSWORD = "passwd"
DATABASE_NAME = "app"
DATABASE_PORT_OUTER = 5432
DATABASE_PORT_INNER = 5432
REDIS_PORT_OUTER = 6379
REDIS_PORT_INNER = 6379
AUTH_TOKEN_TTL = 86400

[tasks.set-env-local.env]
DATABASE_HOST = "localhost"
DATABASE_URL = "postgresql://${DATABASE_HOST}:${DATABASE_PORT_INNER}/${DATABASE_NAME}?user=${DATABASE_USERNAME}&password=${DATABASE_PASSWORD}"

[tasks.reset]
run_task = [
    { name = [
        "dc-down",
        "dc-up",
        "migrate",
    ] },
]

[tasks.dc-up]
extend = "set-env-local"
command = "docker"
args = ["compose", "up", "-d"]

[tasks.dc-down]
command = "docker"
args = ["compose", "down"]

[tasks.test]
extend = "set-env-local"
install_crate = { crate_name =  "cargo-nextest", binary = "cargo", test_args = ["nextest", "--help"] }
command = "cargo"
args = ["nextest", "run", "--workspace", "--status-level", "all", "--test-threads=1"]

[tasks.migrate]
extend = "set-env-local"
install_crate = { crate_name =  "sqlx-cli", binary = "sqlx", test_args = ["--help"], version = "0.7.3" }
command = "sqlx"
args = ["migrate", "run", "--source", "infra/migrations", "--database-url", "${DATABASE_URL}"]

[tasks.gen-entity]
extend = "set-env-local"
command = "sea-orm-cli"
args = ["generate", "entity", "-u", "${DATABASE_URL}", "-o", "./infra/src/orms"]
