[package]
name = "infra"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait.workspace = true
domain.workspace = true
sqlx.workspace = true
shaku.workspace = true
sea-orm.workspace = true
uuid.workspace = true
url.workspace = true
common.workspace = true
