[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
axum.workspace = true
registry.workspace = true
domain.workspace = true
shaku.workspace = true
serde.workspace = true
uuid.workspace = true
url.workspace = true
anyhow.workspace = true
